name: Run All Tests

on:
  push:
    branches: [ csharp ]
  pull_request:
    branches: [ csharp ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout user code
        uses: actions/checkout@v3
      - name: Set .NET 7 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - name: run tests
        run: |
          newman_collectionName=calculator-tests iterationCount=1 web_app_cpu='2' test_driver_cpu='2' docker-compose -f compose-file.yml up --exit-code-from test-driver --build
